exclude: [
    "README.md",
    "node_modules",
    "Gruntfile.js",
    "package.json"
]

baseurl: "http://docs.smarthealthit.org/"
markdown: kramdown
github_branch: master
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
